# Generated by Django 4.0.3 on 2022-04-05 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pizzas", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="topping",
            name="rating",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "Vegan-friendly"),
                    (1, "Vegetarian-friendly"),
                    (2, "Non-vegan non-veg"),
                ],
                default=2,
            ),
            preserve_default=False,
        ),
    ]
